sudo: false

language: perl

git:
  depth: 3
  
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"

# disable cpanm

before_install: true

install: true

before_script:
  - perlbrew use $PERLVERS
  - ./bootstrap

script:
  - ./configure
  - make
  - make dist
  - mkdir ~/src
  - cp pkgmgr*.tar.gz ~/src
  - cd ~/src
  - tar xvf pkgmgr*gz
  - cd pkgmgr*/
  - ./configure --prefix=$HOME/pkgmgr
  - make
  - make install
  - ./bin/pkgmgr version

  - perl ./t/srcdstrepo.t || test $? == 1
